config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :edit, :update, :show]

  resources :teams, only: [:create, :show] do
    resources :projects, only: [:index, :new, :create]
    resources :events, only: :index
  end

  resources :projects, only: [:show, :edit, :update, :destroy] do
    post :do_archived, :do_unarchived, on: :member

    resources :todos, only: [:new, :create]
  end

  resources :todos, only: [:show, :edit, :update, :destroy] do
    post :do_runing, :do_pause, :do_completed, :do_reorder, :recover, on: :member

    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:edit, :update, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :trackable, polymorphic: true

  serialize :data, JSON
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsGroupable

  def index
    current_user_resource_ids = current_user.resource_ids
    @per_page       = 50
    page_num        = params[:page].to_i
    all_team_events = Event.where(team_id: params[:team_id], resource_id: current_user_resource_ids).order(id: :desc)
    @events_count   = all_team_events.count
    team_events =
      if page_num <= 1
        all_team_events.limit(@per_page)
      else
        all_team_events.offset(@per_page * (page_num - 1)).limit(@per_page)
      end
    @team_events_hash = team_events_hash_with(team_events)
    @total_page       = (@events_count / @per_page.to_f).ceil

    if request.xhr?
      render partial: 'team', locals: { team_events_hash: @team_events_hash }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  # 设置完成日期文案
  def event_due_at_pre(pre_date)
    pre_date.nil? ? '没有截止日期' : Date.parse(pre_date)
  end

  # 设置完成日期文案
  def event_due_at_after(after_date)
    after_date.nil? ? '没有截止日期' : Date.parse(after_date)
  end

  # 指派任务文案
  def event_assign_with(prev, after)
    return "给 #{after} 指派了任务" if prev.nil?
    return "取消了 #{prev} 的任务" if after.nil?
    return "将 #{prev} 的任务指派给 #{after}"
  end

  # 动作名称
  def event_action_name_with(action)
    I18n.t(action, scope: 'activerecord.attributes.event.action_enum', default: '无')
  end

  def event_trackable_type
    {Team: '团队', Project: '项目', Todo: '任务'}
  end

  def event_redirect_url_with(id, type)
    "#{ENV['SITE_HOST']}/#{type.underscore}s/#{id}"
  end
end

app/views/events/_assign.html.erb
<%= event_assign_with(event[:prev], event[:after]) %>

app/views/events/_create.html.erb
<%= "#{event_action_name_with(event[:action])}#{event_trackable_type[event[:trackable_type].to_sym]}" %>

app/views/events/_create_comment.html.erb
<%= "#{event_action_name_with(event[:action])}#{event_trackable_type[event[:trackable_type].to_sym]}" %>

app/views/events/_destroy.html.erb
<%= "#{event_action_name_with(event[:action])}#{event_trackable_type[event[:trackable_type].to_sym]}" %>

app/views/events/_destroy_comment.erb
<%= "#{event_action_name_with(event[:action])}#{event_trackable_type[event[:trackable_type].to_sym]}" %>

app/views/events/_event_common.html.erb
<div class="event event-common">
  <%= link_to image_tag("avatar/small_default.png"), user_path(event[:actor_id]), class: 'from', target: '_blank' %>
  <div class="event-main">
    <div class="event-head">
      <%= link_to event[:created_at], '#', class: 'event-created-at' %>
      <span class="event-actor">
        <%= link_to event[:actor_name], user_path(event[:actor_id]), class: 'link-member', target: '_blank' %>
      </span>
      <span class="event-actoin">
        <%= render partial: "#{event[:action]}", locals: { event: event } %>
      </span>
      <span class="event-text">
        <span class="emphasize">
          <% if event[:priority] %>
            <em class="priority"><%= event[:priority] %></em>
          <% end %>
          <% if event[:tag] %>
            <%= link_to event[:tag], '#', class: 'tag' %>
          <% end %>
          <%= link_to event[:trackable_name], event_redirect_url_with(event[:trackable_id], event[:trackable_type]), target: '_blank' %>
        </span>
      </span>
    </div>
    <% if event[:action].end_with?('comment') %>
      <div class="event-body">
        <span class="event-text"><%= event[:comment_content] %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_recover.html.erb
<%= "#{event_action_name_with(event[:action])}#{event_trackable_type[event[:trackable_type].to_sym]}" %>

app/views/events/_set_due.html.erb
<%= event[:action] %>
<span class="data-readable-date"><%= event_due_at_pre(event[:prev]) %></span>
修改为
<span class="data-readable-date"><%= event_due_at_after(event[:after]) %></span>

app/views/events/_set_due_at.html.erb
<%= event_action_name_with(event[:action]) %>
<span class="data-readable-date"><%= event_due_at_pre(event[:prev]) %></span>
修改为
<span class="data-readable-date"><%= event_due_at_after(event[:after]) %></span>

app/views/events/_status_transaction.html.erb
<%= "#{event_action_name_with(event[:after])}#{event_trackable_type[event[:trackable_type].to_sym]}" %>

app/views/events/_status_transition.html.erb
<%= "#{event_action_name_with(event[:after])}#{event_trackable_type[event[:trackable_type].to_sym]}" %>

app/views/events/_team.html.erb
<% team_events_hash.each do |event_hash| %>
  <div class="events-day">
    <h4 class="events-day-title">
      <span class="date"><%= event_hash[:created_date] %></span>
    </h4>
    <div class="events-day-content">
      <% event_hash[:items].each do |item| %>
        <div class="events-ancestor">
          <h5 class="events-ancestor-title"><%= link_to item[:category], event_redirect_url_with(item[:ancestor_id], item[:ancestor_type]), target: '_blank' %></h5>
          <% item[:events].each do |event| %>
            <%= render partial: 'event_common', locals: { event: event } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="page page-root">
  <div class="page-inner" id="page-events">
    <div class="filters">
    </div>
    <div class="team-events" data-total-page=<%= @total_page %> data-team-id=<%= params[:team_id] %>>
      <%= render partial: 'team', locals: { team_events_hash: @team_events_hash } %>
      <% if @events_count <= @per_page %>
        <a>没有更多内容了</a>
      <% else %>
        <a id="inifiniteLoader">加载更多内容... </a>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  Events.InfiniteScroll.infiniteScroll();
</script>